spring:
  application:
    name: omnicloud

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/omnicloud_db
    username: postgres
    password: postgres

  sql:
    init:
      mode: always

server:
  port: 8080

logging:
  level:
    org.springframework: INFO
    com.omnicloud: DEBUG